import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import Navbar from "../components/navbar";

const Home: NextPage = () => {
  return (
      <div className="bg-slate-900 min-h-screen">
          <Navbar/>
          <div className="text-gray-300 p-5">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquam erat ac ipsum vulputate commodo eget ut mi. Sed ut volutpat tellus. Donec porttitor neque id arcu viverra, quis posuere lorem efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras sed viverra mi. In nulla odio, scelerisque auctor lorem ac, maximus porta est. Mauris in tellus eget diam mollis blandit sed at nulla. Vestibulum a mollis massa. Maecenas nec enim et risus consectetur rhoncus. Suspendisse imperdiet tellus consectetur, interdum sem ut, viverra lectus.

              Morbi non interdum nisi. Cras bibendum mollis lorem sed pharetra. Nulla sed ligula diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque in luctus nulla. Phasellus ac diam in tortor venenatis hendrerit nec ac ante. Sed congue sollicitudin semper. Aliquam sed leo suscipit, posuere ex ut, volutpat leo. Proin et faucibus diam. Donec ac pharetra leo, viverra pretium dui. Suspendisse bibendum semper eros. Nunc condimentum aliquam elit sed molestie. Suspendisse a tellus luctus, blandit justo ac, interdum nisl. Nullam efficitur dictum ante, eu ultricies dolor ultricies id.

              Nulla laoreet hendrerit vehicula. Praesent egestas et mauris ac suscipit. Aliquam eu aliquet metus. Nam et tellus in augue blandit bibendum nec sit amet ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nec magna eu velit suscipit interdum at quis felis. Fusce sapien orci, luctus nec arcu id, rutrum vehicula enim. Suspendisse ac dolor eu enim laoreet sodales non venenatis felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

              Integer ligula lorem, vulputate in ultrices porttitor, tincidunt at nulla. Etiam bibendum lacus ac varius suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in felis laoreet, vehicula mauris ut, fringilla est. Ut finibus nunc vel venenatis vestibulum. Morbi quis metus porttitor, imperdiet magna vitae, feugiat ante. In hac habitasse platea dictumst. Vestibulum et condimentum mauris. Praesent facilisis luctus metus. Nunc mi augue, volutpat ut quam quis, tristique facilisis libero.

              Nunc lacinia nisl quis sem tempus volutpat. Vivamus non nunc ac lorem ultricies facilisis non id nunc. Aliquam vel velit nisi. Suspendisse leo augue, dignissim sit amet venenatis et, laoreet in ligula. Nunc eu gravida augue. Vestibulum consequat fringilla libero eget ultricies. Sed facilisis urna et lacus iaculis, sed imperdiet lorem malesuada. In vel velit porta, pharetra odio in, sagittis magna. Proin eleifend accumsan nulla, ac mattis tortor pulvinar non. Phasellus lacus nisi, ultrices nec nibh vitae, ullamcorper tempor mi.

              Ut luctus, enim sed facilisis volutpat, enim nisl auctor velit, dignissim interdum tortor nunc vitae diam. Aliquam sodales massa vitae urna pulvinar, vitae condimentum quam sodales. Sed quis felis urna. In rutrum urna eu nibh sodales, tempor tincidunt risus varius. In ornare faucibus tempor. Fusce accumsan suscipit ultricies. Nunc posuere magna ac arcu fringilla vehicula. Etiam nec sagittis risus. Etiam sodales lectus at quam convallis, sodales congue ante tincidunt. Sed eu urna non eros vulputate auctor. Mauris nec eleifend est. Etiam posuere maximus ante ac mattis.

              Fusce a turpis et neque ornare mollis et et elit. Sed dapibus et ex eget finibus. Donec tempor turpis at lorem cursus sodales. Fusce diam diam, imperdiet sed velit vel, imperdiet interdum massa. Integer blandit massa id rhoncus consectetur. Etiam posuere dolor semper purus scelerisque, vitae gravida lorem sollicitudin. Maecenas auctor ex at massa suscipit molestie. Aenean vestibulum, dolor quis feugiat vehicula, erat nunc aliquet enim, ultricies lacinia lectus ipsum a justo. Sed enim lorem, ullamcorper in gravida sollicitudin, congue commodo ipsum. Vestibulum tincidunt tempus dui nec imperdiet. Duis finibus lacus nisi, ut posuere erat egestas vel. Nulla blandit eu enim vel mollis. Nunc justo dui, malesuada eget consequat at, finibus suscipit quam. Nam vitae lacus a quam faucibus eleifend. Ut sagittis placerat elementum.

              Integer eget ipsum feugiat, fermentum urna nec, viverra sapien. Suspendisse dictum vel massa eu bibendum. Morbi sodales dui sit amet purus condimentum, sed malesuada justo sollicitudin. Duis pulvinar mi quis quam ornare, sed dignissim ex malesuada. Fusce viverra nibh a dolor vulputate pretium. Vivamus aliquam ex sem, sed luctus ante sollicitudin at. Aliquam vitae lacus ligula.

              Donec eget leo tristique elit fermentum aliquam. Maecenas ultricies, enim eget porta accumsan, neque sapien viverra felis, eget cursus enim enim in lorem. Sed ornare sem non dolor tincidunt, quis molestie lorem sagittis. Proin lectus neque, consectetur ac bibendum nec, sodales vitae erat. Phasellus eu pharetra ligula. Morbi est est, ullamcorper at libero vitae, convallis tempus mauris. Aliquam erat volutpat. Vivamus ultricies eu massa non finibus. Phasellus sed tellus interdum diam tristique venenatis sed nec lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur quis arcu mattis, semper lectus in, rutrum lorem.

              Aenean est arcu, sollicitudin faucibus diam id, finibus dignissim ante. Aliquam consequat id tellus vel pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a dolor cursus lacus consequat suscipit. Curabitur quis libero maximus, porta augue at, tincidunt velit. Fusce tempor congue dui, sed viverra augue varius in. Nam condimentum tellus eget turpis ultricies tristique. Nam a elit suscipit, cursus eros quis, molestie odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla non libero eget ipsum tristique finibus in nec augue. Mauris id auctor metus. Proin quis bibendum quam, quis imperdiet neque. Morbi vel eros erat. Aenean consequat porttitor pretium. Vestibulum vel sapien ut ex vestibulum rhoncus.

              Phasellus id risus nec libero aliquet commodo vitae a ipsum. Aliquam nec vulputate augue. Sed eu ipsum tortor. Quisque condimentum est nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus tellus est, vulputate vitae turpis non, dignissim imperdiet lectus. Nullam tempus finibus risus. Vestibulum ultricies fermentum ipsum, vitae finibus nisi porta ut.

              Mauris maximus, dui sit amet iaculis hendrerit, magna justo finibus quam, eu vehicula turpis sapien id augue. Sed dictum mi sit amet sem mollis, at accumsan tortor elementum. Quisque et nunc dolor. Mauris mollis, lacus sit amet molestie pharetra, quam magna facilisis arcu, quis sollicitudin mauris massa id quam. Suspendisse eget ex tempus, euismod mauris vel, placerat erat. Phasellus dictum, elit sed tincidunt finibus, turpis metus gravida tortor, eget posuere sapien neque id magna. Ut consectetur nisi vitae pulvinar egestas.

              Vestibulum vel orci in magna molestie viverra. Maecenas aliquam, ex eget pharetra consequat, dolor mauris tristique elit, ut porttitor dui libero luctus nulla. Aenean sollicitudin mi a dui commodo, eu eleifend sem tristique. Vivamus iaculis tempus pellentesque. Integer malesuada purus ex, hendrerit faucibus libero auctor ut. Etiam vel ex leo. Sed ut neque et sapien facilisis fermentum. Vivamus venenatis felis et ante rutrum, volutpat venenatis enim laoreet. Ut eget dignissim ex. Morbi condimentum at metus non bibendum.

              Phasellus quis maximus mi, vel ultricies metus. Sed gravida arcu non ligula vehicula, id mattis ligula auctor. Morbi sit amet dolor sit amet est tempor scelerisque. Nulla sed fermentum diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus neque sem, tristique id lobortis sit amet, lobortis gravida sem. Proin elementum velit ut massa sodales, at accumsan justo cursus. Donec elit risus, feugiat quis ex eu, tincidunt porttitor elit. Morbi semper turpis sed nulla efficitur pretium. Pellentesque in diam molestie, consectetur odio ut, finibus nisi. Integer egestas laoreet elit, ut interdum est ullamcorper id. Phasellus convallis ac orci ut dapibus. Praesent urna neque, tempor eget auctor at, condimentum eget orci. Cras sit amet eros sem. Vestibulum a nisl id enim pharetra condimentum at et nulla.

              Fusce eu tincidunt arcu. Fusce semper a orci id imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mi est. Vivamus molestie, velit nec iaculis auctor, mi erat maximus arcu, sed molestie arcu massa sed diam. Vestibulum non blandit mauris. Cras ac diam augue. Aliquam in luctus quam. Integer elementum elit id dui dapibus, nec consequat odio finibus.

              Nunc ligula dui, convallis a arcu in, molestie mollis augue. Phasellus sed lobortis velit. Nam luctus diam a sollicitudin fringilla. Proin venenatis, tortor ut semper vehicula, felis ligula ullamcorper orci, eget ornare risus mauris ut nisi. Duis id felis vulputate, mollis ante nec, consequat enim. In hac habitasse platea dictumst. Duis condimentum ex leo, nec rutrum magna vestibulum et. Suspendisse sit amet purus porttitor, volutpat mauris et, rutrum leo. Phasellus et enim est.

              Pellentesque laoreet, leo ac scelerisque molestie, neque nunc dapibus est, eu gravida felis dui sit amet orci. Pellentesque in bibendum metus, eu ullamcorper purus. Proin gravida maximus feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse dapibus eros quis nulla rutrum, id accumsan sem porta. In at ex blandit, ultrices lectus quis, commodo ex. Phasellus lorem erat, rhoncus at nulla ut, consectetur consequat nunc.

              Donec pellentesque nisl vitae condimentum aliquam. Suspendisse imperdiet lacus eget mi imperdiet, eget consequat velit pretium. Morbi consequat purus quis risus facilisis ultrices. Nam pretium commodo venenatis. In dapibus, est auctor feugiat rhoncus, diam orci aliquam erat, eu mollis tortor dolor et dolor. Vivamus sit amet elementum metus. Sed purus orci, molestie sit amet pellentesque eget, consectetur a purus. Praesent aliquet enim id malesuada ultricies. Pellentesque sed tellus ultricies, tempor quam quis, rhoncus diam. Aenean vel vestibulum ligula, eget varius est. Curabitur ac volutpat libero, at cursus quam. Aliquam sed nulla lectus. Quisque quis pulvinar turpis, sed aliquet nisl. Ut venenatis metus nisl, non rhoncus enim pellentesque quis. Vestibulum tincidunt molestie lectus, a pulvinar nulla mattis vitae. Proin a risus eu nulla sodales rhoncus varius vitae nisi.

              Suspendisse blandit turpis ac arcu gravida molestie. Sed urna felis, efficitur id malesuada sit amet, iaculis eget justo. Nunc hendrerit eros auctor ornare tincidunt. Sed dictum feugiat ligula, eget faucibus sapien imperdiet in. Nullam tincidunt luctus purus sodales lobortis. Curabitur et erat porta, lobortis dolor eu, aliquet orci. Nam aliquam massa nec enim dictum dignissim et bibendum turpis. Morbi vitae aliquam risus. Vestibulum ultrices massa in urna blandit accumsan. Pellentesque eget tempor purus, cursus tristique dolor. Curabitur sed turpis eget dui pulvinar elementum.

              Quisque at neque magna. Donec imperdiet dictum sollicitudin. Donec fermentum turpis non est accumsan, at congue nunc faucibus. Pellentesque eu ullamcorper ligula, sed rhoncus tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque nec libero tempor, sodales velit id, ullamcorper enim. Vestibulum elit sapien, pellentesque in libero eget, porttitor tempus est. Sed lorem velit, molestie et mi ut, pretium viverra magna. Morbi rhoncus arcu eget nulla pulvinar pellentesque.

              Donec posuere lacus eu velit fringilla, a dignissim metus dictum. Phasellus dolor quam, ultrices et nisi interdum, varius elementum elit. Curabitur vitae tempus eros. Aliquam erat volutpat. Nulla cursus ante at quam suscipit varius. Proin justo lacus, rhoncus nec libero vel, porttitor pharetra sem. In dictum sit amet dui non cursus.

              Proin ac dui a purus volutpat rhoncus ut sed turpis. Etiam eu velit laoreet mauris commodo viverra mollis in lorem. Mauris condimentum sem et elementum feugiat. Vestibulum et luctus elit. Nunc sodales mattis scelerisque. Aenean aliquam dolor et mauris eleifend, in feugiat dolor lacinia. Mauris nec metus diam. Aenean non nunc et quam hendrerit dignissim. Curabitur sit amet consequat augue, nec euismod dui. Sed malesuada erat ut augue euismod interdum. Donec augue nisl, molestie et faucibus a, dictum et lacus. Ut vestibulum nunc ut faucibus hendrerit. Maecenas vitae feugiat metus. Duis posuere nulla a nisi dignissim vehicula. Proin accumsan pulvinar metus, ac viverra nisl volutpat nec.

              Suspendisse nec pretium erat, vel dictum elit. Duis porta, nunc et pharetra elementum, metus orci posuere tellus, vel placerat nisi leo sed elit. Phasellus aliquam, leo eu cursus vulputate, urna urna sagittis erat, ut aliquet sem orci vel mi. Sed et maximus leo. Ut a efficitur enim. Integer at leo eu lacus pulvinar porta vel at ligula. Maecenas eu hendrerit nisi, et ullamcorper odio. Cras quam turpis, convallis at dui ac, facilisis facilisis sapien. Maecenas non odio ut tortor iaculis semper vel vel tellus. Pellentesque rutrum pellentesque iaculis. Maecenas pulvinar, augue eu ultricies efficitur, tortor neque convallis nibh, in blandit diam lacus in mi. Nulla facilisi. Nam lacus tellus, euismod eget arcu tincidunt, elementum laoreet ligula.

              Donec porttitor nisl sed libero euismod, ac pulvinar dui gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus volutpat laoreet arcu et vulputate. Fusce suscipit turpis eget mauris hendrerit consectetur. Donec lobortis elementum porttitor. Nam pretium velit et euismod interdum. Curabitur vel tristique ante, dapibus tincidunt felis. Fusce sed iaculis dolor. Morbi efficitur nisl in lectus hendrerit, id vestibulum lacus vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur rhoncus neque vitae sodales porttitor. Suspendisse potenti. Maecenas non luctus lectus, pulvinar condimentum orci. Donec a ultrices justo.

              Sed ac malesuada nisl. In et arcu dolor. Nullam non ligula laoreet, bibendum nibh sed, volutpat nulla. Integer in bibendum nisl. Quisque consequat lacus purus, nec blandit magna blandit ut. Donec maximus eleifend justo, eu consequat tortor finibus eget. Aenean leo nibh, efficitur vel est quis, ullamcorper ultrices ante. Integer hendrerit sem a enim accumsan luctus. Cras tempor nisl quis sagittis volutpat. Maecenas non lobortis ligula, in ornare odio.

              Donec consequat neque id sodales ullamcorper. Morbi tempus turpis vitae orci facilisis, sed porttitor turpis auctor. Nullam efficitur metus massa, vel scelerisque neque posuere ac. Praesent finibus ultrices libero, a molestie dui luctus ut. Nulla arcu lorem, bibendum sed nunc sed, feugiat venenatis ex. Cras sed arcu iaculis, scelerisque enim ut, sagittis quam. Nullam lobortis elit lacus, eget volutpat leo tincidunt id. Fusce facilisis lectus vel convallis aliquam.

              Curabitur ante erat, rutrum ac erat ut, ultricies tempor mauris. Pellentesque risus ligula, finibus quis enim sit amet, varius egestas nisi. Sed ante metus, auctor ac iaculis id, pellentesque ut lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus suscipit, libero at tincidunt hendrerit, turpis mauris auctor turpis, vitae imperdiet sem lorem eu lacus. Nunc ultrices placerat tristique. Pellentesque ex ante, suscipit sed iaculis vitae, laoreet sit amet nulla. Etiam rutrum volutpat varius. Donec tellus neque, commodo non nibh eu, molestie congue leo.

              Vivamus ac pharetra urna, volutpat ornare ex. Maecenas varius feugiat sollicitudin. Curabitur ultricies purus ipsum, vitae hendrerit tellus auctor quis. Integer pretium ut ante in pretium. Praesent lobortis ornare purus, eget blandit mauris sagittis volutpat. In luctus justo sed maximus condimentum. Nunc et posuere arcu.

              Sed aliquet purus orci. Donec quis cursus tortor. Maecenas sed nunc lacus. Etiam rutrum sagittis purus id bibendum. Curabitur semper euismod felis quis tempus. Quisque volutpat, felis quis rutrum mattis, turpis eros efficitur ligula, non commodo urna odio a libero. Quisque sed nisi mauris. Pellentesque congue ac nunc sit amet fringilla. Cras ut euismod elit. Donec dapibus nisi purus, a consectetur leo suscipit at. Suspendisse in nunc tortor. Maecenas odio ipsum, aliquet eu metus at, ultricies imperdiet sem. Ut congue ante blandit nisl finibus, eget tincidunt dui pellentesque. Integer non turpis hendrerit, egestas tortor sed, facilisis augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

              Vestibulum et scelerisque mauris. Phasellus ornare, felis nec malesuada euismod, leo eros porttitor tortor, vitae placerat turpis dolor et tellus. Ut ac congue nulla. Sed mi orci, volutpat eu varius sed, bibendum nec ipsum. Praesent blandit non eros a tristique. Mauris bibendum risus dapibus purus egestas, et tincidunt metus finibus. Donec auctor, quam quis convallis vehicula, velit quam fringilla velit, nec consectetur tortor velit quis massa.
          </div>
          
      </div>
  )
}

export default Home
